apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-volo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-volo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-volo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-volo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-volo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ipxm-tenant/rhtap-demo-app/hacbs-test-project-volo@sha256:265f89026dc49d18357c04b8b5633091ecd6ee5c4d72cd5c6bc35bc56f9ceea0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
